// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_QV17Nxh3p2YHxdc8nTiIbRKOgKnyW44',
    appId: '1:400334870383:android:e45c1e066af7245424fa9a',
    messagingSenderId: '400334870383',
    projectId: 'prevent-5e4a8',
    storageBucket: 'prevent-5e4a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlYtsuq5ug77D7LC6HJCsP9eoBSc7XP9U',
    appId: '1:400334870383:ios:76439c4217c7f5c024fa9a',
    messagingSenderId: '400334870383',
    projectId: 'prevent-5e4a8',
    storageBucket: 'prevent-5e4a8.firebasestorage.app',
    androidClientId: '400334870383-o11s6fo5gn9r6k7ptd1kmf0482nfqk4i.apps.googleusercontent.com',
    iosClientId: '400334870383-ff9p253ta0rdms0vv5r9q8cl728ni888.apps.googleusercontent.com',
    iosBundleId: 'ca.turbovets.turbovets',
  );
}
